
export const Rest = {
    // Headers
    X_TOTAL_COUNT: "X-Total-Count",
    X_SERVICE_NAME: "X-Service-Name",
    X_SERVICE_VERSION: "X-Service-Version",
    X_SERVICE_ENV: "X-Service-Env",
    AUTHORIZATION: "Authorization",
    WWW_AUTHENTICATE: "WWW-Authenticate",
    LOCATION: "Location",
    
    // Statuses
    STATUS_OK: 200,
    STATUS_CREATED: 201,
    STATUS_NO_CONTENT: 204,
    STATUS_BAD_REQUEST: 400,
    STATUS_UNAUTHORIZED: 401,
    STATUS_FORBIDDEN: 403,
    STATUS_NOT_FOUND: 404,
    STATUS_CONFLICT: 409,
    STATUS_UNPROCESSABLE_ENTITY: 422,
    STATUS_INTERNAL_SERVER_ERROR: 500,
    STATUS_SERVICE_UNAVAILABLE: 503,
};
