services:
  - docker

language: node_js
dist: trusty
node_js:
  - '12'

branches:
  only:
    - develop

cache:
  directories:
    - ./node_modules

env:
  global:
    - DOCKER_IMAGE=docker.mjamsek.com/ping-api:latest

install: npm install

script:
  - npm run build
  - docker build -t $DOCKER_IMAGE .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" docker.mjamsek.com
  - docker push $DOCKER_IMAGE

notifications:
  email: false
  slack:
    rooms:
      - secure: U6gbxhULx57zp88z7uh1/me6+4LsfCFUuuyGdFxqzZwwTlSN8ylbvH3gzenXIN0p4H31boNhGtQTlhQczBXIUbpirVoQkDMROArcK2o1fOuJ2MCma+J4wVtxgZDcoype9cC7dZQT390wAwVfufHbAJvcSoiRYoQs3E59ulvhPJrZSFtCmn5rRq4HjjXJu31ADJcVUgE9WSYw1npnMuAB8TCe7vL86sPtsmOdqKpUyoVvdw52rHyN0DCYbIbsPBO1XQj+UcT/P3EwW46Y3Tv7qQu+FlMgowdmiPRghlW7zB4Hw/JIGyoNVfK7JlgWHR1Cp04koL9jY2FxL67dSdXfRLYh9PH1AVdbKw/yRNZheV4iPHnMpoFXAxm9597zYXcYBDxH4KqTkoeI8rX3v+nEaVjAqEEZaV7MY1r+kWVvOEEJTej93wht6nmEw2y9/6p3NTOLI9Zz0s5uHQus/3VGMh5VV/1xXwUsP2DHN+lRHX73w1GSEs1D4AE3Kq5Mx8CVhStQSzwC1tcwQrHNVXBOmreEdZ0p808TSMgUVqSdmsPS6ilwJiTtxVAjcAmHtnPRtp8GOtqyvqOVQ8dHe/FoRp9LmYEsERkf06LIVv00ov1se5DGwuLElV7QE26nKIBHs7kgq9M6ppsTMYs+W/gbanxeHYcdVRqcijJl8pOM2ko=
    on_success: always
    on_failure: always
    template:
      - "`%{result}` build for repo `%{repository_slug}` on branch `%{branch}`. Build (<%{build_url}|#%{build_number}>). Commit (<%{compare_url}|%{commit}>)."
      - "Execution time: *%{duration}*"
      - "Message: *%{message}*"
